services:
  - type: web
    name: kishanmitra-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE
        sync: false
      - key: USER_PHONE
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: HF_REPO_ID
        sync: false
    healthCheckPath: /docs
